### ISSUE TITLE
Backup and restore settings (uYou, uYouEnhanced, YT & etc.)

### ISSUE THREAD

**Issue by KarmaBeast** [arichornlover/uYouEnhanced#609]
Please add a backup and restore settings option. Otherwise I have to take screenshots of each sections because I can never remember how I configured all my tweaks.

(In the case that deleting and reinstalling the app is becomes necessary due to installation/updating errors, like I'm facing now...)

**Comment by bhackel** [comment]
Yes I will be working on this soon

**Comment by bhackel** [comment]
Nice that’s pretty much what I was thinking of - now we just need to find all the keys…

**Comment by bhackel** [comment]
That is true, but I also want to get all of the uYou keys and maybe some of the YouTube keys as well. Will work on it soon

**Comment by bhackel** [comment]
Ah nice work, that is good to hear

**Comment by bhackel** [comment]
Hey @arichornlover I noticed that some keys, like uYou's default wifi quality (the key is `wifiQuality`), use values like `auto`, `1080p60`, and other things. I think we need to change these lines:
```obj-c
BOOL value = [components[1] intValue];
[[NSUserDefaults standardUserDefaults] setBool:value forKey:key];
```
so that they can support strings as the value, somehow. I will look into it in a few days when I have some free time, unless you can figure it out before then.

**Comment by jianmingyong** [comment]
This feature is also useful when the app crashes and forcefully reset all settings making you having to set up all over again and again.
