### ISSUE TITLE
[Questions] So what's the deal with this repo now? How do I get the latest?

### ISSUE THREAD

**Issue by jaycomma** [arichornlover/uYouEnhanced#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I have not compiled a new version of the app in months and it's starting to show. I'm pretty confused on what's going on here in this repo because the latest release was months ago and that is really unlike arichornlover. Have the latest releases been moved to a different website because of the ban a while back?

Please let me know, I hate being out of the loop! Thank you!

**Comment by yodaluca23** [comment]
You have to build your own now, because of the DMCA from Google. And they cannot be shared.

https://github.com/arichornlover/uYouEnhanced/wiki/Building

It's very easy, you just need to procure your own vanilla YouTube .ipa. Which for obvious reasons cannot be shared, you can find websites online that have them or telegram bots. I personally would just get a jailbroken device and decrypt it yourself though.

**Comment by yodaluca23** [comment]
> Oh I know that we have to build it, but it seems this repo is pretty out of date. I found the IPA on the new location but it is pretty buggy and ads show on shorts :/ 

You have to build it if you want the latest commits anyone you find online is gonna be very old...

**Comment by karolba** [comment]
The release dates are meaningless now, don't look at them - build from the `main` branch
